### ISSUE TITLE
[COVID_GAN3.py] target size error

### ISSUE THREAD

**Issue by danny0628** [dinhgit/FL-GAN_COVID#1]
I try to run COVID_GAN3.py, following error occured.
How can I solve it?

```
/home/mjkim1/workspace/FL-GAN_COVID/model_GAN3.py:112: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  c = self.softmax(c)
Traceback (most recent call last):
  File "COVID_GAN3.py", line 282, in <module>
    y  = training()     
  File "COVID_GAN3.py", line 153, in training
    s_errD_real =  nn.BCELoss()(s_output, s_label)
  File "/home/mjkim1/.conda/envs/fl_gan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mjkim1/.conda/envs/fl_gan/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 612, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/mjkim1/.conda/envs/fl_gan/lib/python3.7/site-packages/torch/nn/functional.py", line 2886, in binary_cross_entropy
    "Please ensure they have the same size.".format(target.size(), input.size())
ValueError: Using a target size (torch.Size([16])) that is different to the input size (torch.Size([16, 1])) is deprecated. Please ensure they have the same size.
```

**Comment by CJPYa** [comment]
Yeah, I also met a such problem, so did you solve it untill now?
